import Form from '@/components/Form'
import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='contenedor'>
          <div className='columna-izquierda'>
            <div className='registro activo' id='registro'>
              <div className='header'>
                <h1>Fiesta Domingo de Carnaval</h1>
                <p>Personal para manillas</p>
              </div>

              <Form />
            </div>

            <div className='header exito' id='exito'>
              <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' className='bi bi-check-circle' viewBox='0 0 16 16'>
                <path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z' />
                <path d='M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z' />
              </svg>
              <h1>Registrado!</h1>
              <p>Te mandaremos un correo electrónico si resultas ganador.</p>
            </div>
          </div>

        </div>

      </main>
    </>
  )
}
